### ISSUE TITLE
can not login

### ISSUE THREAD

**Issue by NadaBen** [ridwannaruto/JobBank#1]
Hello
I'm trying to use your project, when i validate email to activate user account  it shows me  Success! 

Message:Email confirmation is done. Please contact wait till we activate your Account
 But i can not login with it, how to fix that please ?

**Comment by nadundesilva** [comment]
This is not an issue in the system. This project was designed to support verification and activation as two processes that should happen consecutively. Verifying via email will set the "status" field in the user table to "1". Then an admin needs to activate the user which will make the status "2".

In the first time using the system you would have to set the status as "2" in the database manually. And make sure you set the "accesslevel" field in the user table to "admin" so that you can do the above process using the system next time.

**Comment by NadaBen** [comment]
Okey thank you
